
# https://zensical.org/docs/get-started/

[project]
  site_name = "python-package-template"
  site_description = "Python package template configuration."
  site_author = "Daniel Mizsak"
  site_url = "https://daniel-mizsak.github.io/python-package-template/"
  site_dir = ".artifacts/site"

  repo_name = "python-package-template"
  repo_url = "https://github.com/daniel-mizsak/python-package-template/"

  nav = [
    { "Getting started" = [
      "index.md",
    ] },
    { "Tools" = [
      "tools/index.md",
      { "Just" = "tools/just.md" },
      { "Uv" = "tools/uv.md" },
      { "Ruff" = "tools/ruff.md" },
      { "MyPy" = "tools/mypy.md" },
      { "Pytest" = "tools/pytest.md" },
      { "Nox" = "tools/nox.md" },
      { "Megalinter" = "tools/megalinter.md" },
      { "Pre-Commit" = "tools/pre-commit.md" },
      { "Codecov" = "tools/codecov.md" },
      { "Zensical" = "tools/zensical.md" },
      { "GitHub Pages" = "tools/github-pages.md" },
      { "PyPI" = "tools/pypi.md" },
    ] },
    { "Reference" = [
      { "Add Five" = "reference/add_five.md" },
      { "Subtract Three" = "reference/subtract_three.md" },
    ] },
  ]

  [project.theme]
    variant = "classis"
    logo = "assets/logo.png"
    favicon = "assets/logo.png"
    features = [
      "content.code.annotate",
      "content.code.copy",
      "navigation.footer",
      "navigation.indexes",
      "navigation.tabs",
      "navigation.tabs.sticky",
      "navigation.top",
      "search.highlight",
      "search.suggest",
    ]
    # Palette toggle for automatic mode
    [[project.theme.palette]]
      media = "(prefers-color-scheme)"
      toggle.icon = "lucide/sun-moon"
      toggle.name = "Switch to light mode"

    # Palette toggle for light mode
    [[project.theme.palette]]
      media = "(prefers-color-scheme: light)"
      scheme = "default"
      toggle.icon = "lucide/sun"
      toggle.name = "Switch to dark mode"

    # Palette toggle for dark mode
    [[project.theme.palette]]
      media = "(prefers-color-scheme: dark)"
      scheme = "slate"
      toggle.icon = "lucide/moon"
      toggle.name = "Switch to system preference"

  [project.plugins.mkdocstrings.handlers.python]
    inventories = ["https://docs.python.org/3/objects.inv"]
    paths = ["src"]

    [project.plugins.mkdocstrings.handlers.python.options]
      docstring_style = "google"
      members_order = "source"
      show_if_no_docstring = true
      show_root_heading = true
      show_signature_annotations = true
      show_source = false
      show_symbol_type_heading = true
      show_symbol_type_toc = true

  [project.markdown_extensions.admonition]
  [project.markdown_extensions.attr_list]
  [project.markdown_extensions.md_in_html]
  [project.markdown_extensions.pymdownx.details]
  [project.markdown_extensions.pymdownx.emoji]
    emoji_index = "zensical.extensions.emoji.twemoji"
    emoji_generator = "zensical.extensions.emoji.to_svg"
  [project.markdown_extensions.pymdownx.highlight]
    anchor_linenums = true
    line_spans = "__span"
    pygments_lang_class = true
  [project.markdown_extensions.pymdownx.inlinehilite]
  [project.markdown_extensions.pymdownx.snippets]
  [project.markdown_extensions.pymdownx.superfences]
  [project.markdown_extensions.tables]
  [project.markdown_extensions.toc]
    permalink = true

  [project.extra]
    generator = false
